CREATE TABLE INCIDENT(
  SUMMARY VARCHAR(64) NOT NULL,
  DESCRIPTION VARCHAR(256) NOT NULL,
  PRODUCT VARCHAR(32) NOT NULL,
  STOREID VARCHAR(8) NOT NULL,
  NAME VARCHAR(64) NOT NULL,
  PHONENUMBER VARCHAR(32) NOT NULL,
  STATUS VARCHAR(32) NOT NULL,
  ID BIGINT AUTO_INCREMENT PRIMARY KEY
);